### ISSUE TITLE
Error Build

### ISSUE THREAD

**Issue by dralagen** [DreierF/MyTargets#23]
When try to build on branch master to pass siging package, I have this error : 

```
.../MyTargets/app/src/main/java/de/dreier/mytargets/activities/ItemSelectActivity.java:31: error: cannot find symbol
        implements SelectItemFragment.OnItemSelectedListener,
                                     ^
  symbol:   class OnItemSelectedListener
  location: class SelectItemFragment
```

When replace SelectItemFragment by FragmentBase, the app build but when launch I have this erreur : 

```
11-19 09:14:04.368    4909-4909/de.dreier.mytargets E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{de.dreier.mytargets/de.dreier.mytargets.activities.MainActivity}: android.view.InflateException: Binary XML file line #37: Error inflating class android.support.design.widget.FloatingActionButton
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2463)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5751)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #37: Error inflating class android.support.design.widget.FloatingActionButton
            at android.view.LayoutInflater.createView(LayoutInflater.java:613)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:805)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at de.dreier.mytargets.activities.MainActivity.onCreate(MainActivity.java:58)
            at android.app.Activity.performCreate(Activity.java:5165)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5751)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:805)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at de.dreier.mytargets.activities.MainActivity.onCreate(MainActivity.java:58)
            at android.app.Activity.performCreate(Activity.java:5165)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5751)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_add_white_24dp.xml from drawable resource ID #0x7f02007f
            at android.content.res.Resources.loadDrawable(Resources.java:1998)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
            at android.widget.ImageView.<init>(ImageView.java:120)
            at android.widget.ImageButton.<init>(ImageButton.java:87)
            at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:108)
            at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:104)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:805)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at de.dreier.mytargets.activities.MainActivity.onCreate(MainActivity.java:58)
            at android.app.Activity.performCreate(Activity.java:5165)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5751)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
            at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:881)
            at android.graphics.drawable.Drawable.createFromXml(Drawable.java:822)
            at android.content.res.Resources.loadDrawable(Resources.java:1995)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
            at android.widget.ImageView.<init>(ImageView.java:120)
            at android.widget.ImageButton.<init>(ImageButton.java:87)
            at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:108)
            at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:104)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:587)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
            at android.view.LayoutInflater.parseInclude(LayoutInflater.java:805)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:736)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
            at de.dreier.mytargets.activities.MainActivity.onCreate(MainActivity.java:58)
            at android.app.Activity.performCreate(Activity.java:5165)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2520)
            at android.app.ActivityThread.access$600(ActivityThread.java:162)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1366)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5751)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by DreierF** [comment]
Very strange. I'm currently wondering why my compiler is not complaining about the SelectItemFragment.OnItemSelectedListener. On which platform are you trying to build it?
Which version of Android are you using? The runtime error seems to be some issue related to vector drawables. Those are only meant to be used for devices with Android 5.0 and higher. For older systems gradle should automatically generate png's with different resolutions from the provided vector drawables.
You could try switching to a newer version of grade build tools. Just update the version in the root build.gradle from classpath 'com.android.tools.build:gradle:1.3.0' to classpath 'com.android.tools.build:gradle:1.4.0-beta6'.

**Comment by dralagen** [comment]
I'm on Archlinux with java8. I use an android 4.2.2
I try build with Intellij 15 community build and the gradlew in project on command line.

The build error have the same with Gradle:1.3.1 and don't find Gradle:1.4.0-beta6 but I try with 1.5.0

**Comment by dralagen** [comment]
It's work on android 5.1
I think the app are not compatible with older version.

**Comment by DreierF** [comment]
But the current beta works on your phone, does it?

**Comment by DreierF** [comment]
Oh I just saw that I replaced the icons with vector drawables shortly after beta4.

**Comment by DreierF** [comment]
Quote: We are also excited to offer backwards compatibility for your vector assets in **Android Studio 1.4**. Once you have a vectorDrawable image in your res/drawable, the Gradle plugin will automatically generate raster PNG images for API level 20 and below during build time. This means you only need to update and maintain your vector asset for your app project and Android Studio can take care of image conversion process. Note, it is still best practice to create density dependent launcher icons in your res/mipmap folder.

**Comment by dralagen** [comment]
The current beta works. But not when I assemble my own version (not modified).

**Comment by dralagen** [comment]
But android studio are based on intellij so It must be work.

**Comment by DreierF** [comment]
Android Studio is build on top of IntelliJ, but android studio adds a lot of features specific to android development. And as mentioned in the quote, Android Studio takes care of creating the png's for android <5 devices. IntelliJ won't do that for you.

**Comment by dralagen** [comment]
With Android studio, it work on android 4.2.2 but I still have this error : 

```
MyTargets/app/src/main/java/de/dreier/mytargets/activities/ItemSelectActivity.java:31: error: cannot find symbol
        implements SelectItemFragment.OnItemSelectedListener,
                                     ^
  symbol:   class OnItemSelectedListener
  location: class SelectItemFragment
```

**Comment by DreierF** [comment]
Pull from develop. I have fixed it there ;-)

**Comment by DreierF** [comment]
Does it work now?

**Comment by dralagen** [comment]
yes if I use a cherry-pick from https://github.com/DreierF/MyTargets/commit/64c24e5ff651cae19dd7917f7cd934b8c8a3e478 to develop
